import array
arr = array.array('i', [1, 2, 3, 4, 5])
print("Original array:",arr)
arr.append(4)
print("New array:",arr)
arr.insert(1,0)
print("After insertion:",arr)
removal = arr.pop(3)
print(f"removed element at index 3 is: {removal}")
print("Array after pop:",arr)
arr.remove(0)
print("After removal:",arr)
idx = arr.index(5)
print("Index of 5:",idx)
count1 = arr.count(4)
print("Count of 4:",count1)
arr.extend([7, 8, 9, 10])
print("Array after append:",arr)
arr.reverse()
print("Array after reversal:",arr)
copy_array = array.array(arr.typecode, arr[:])
print("The copied array is:",arr)
